# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_schedule',
            name='course_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='demo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='duration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='faculty',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
