# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_django_subject_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=b'documents/%Y/%m/%d')),
            ],
        ),
    ]
