# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='files',
            field=models.FileField(upload_to=b''),
        ),
    ]
