# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160924_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Popup_Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('course', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
