# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_course_popup_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Database_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
