# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_course_database_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_popup_window',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
